"""Rule - Multi-Stage Kill-Chain Correlation (timing-composed).

Correlates otherwise-independent detections into a multi-stage incident.
If several rule families fired for the same user or host within the
window, a higher-severity correlated alert is raised (e.g. brute-force ->
persistence -> lateral movement).

Timing composition (v2): beyond counting stage families, the rule now
reconstructs the *observed sequence* per host/user - each stage's first
alert - and measures two timing facts from the timeline:

* **Ordering** - the fraction of adjacent stage pairs that advance along
  the canonical kill-chain order (``KILL_CHAIN_STAGES``). A chain whose
  stages arrive in expected order (discovery -> execution -> persistence
  -> exfiltration) is a coherent campaign; a reversed or scrambled
  sequence is more likely coincident telemetry and is scored lower.
* **Gap** - the wall-clock span of the chain and the longest gap between
  consecutive stages. A chain with isolated fast sub-steps but a very
  slow overall span is still a chain, but a "slow burn" and fired with
  a softer confidence.

Pure-live: operates on real alerts generated by the live pipeline.
"""
from __future__ import annotations

from datetime import datetime, timedelta, timezone

from sqlalchemy import select

from backend.database.models import Alert
from backend.detection.rules.base import BaseRule, DetectionResult

# Stages ordered by typical kill-chain progression.
KILL_CHAIN_STAGES = {
    # Native rule families
    "email_phishing": "Initial Access",
    "malware_file": "Initial Access / Tool Transfer",
    "brute_force": "Credential Access",
    "suspicious_powershell": "Execution",
    "privilege_escalation": "Privilege Escalation",
    "persistence": "Persistence",
    "data_staging": "Collection",
    "dns_http_exfil": "Exfiltration / C2",
    "lateral_movement": "Lateral Movement",
    "network_recon": "Discovery",
    "usb_device": "Lateral Movement",
    # Initial access (2.1a)
    "spearphishing_attachment": "Initial Access",
    "spearphishing_link": "Initial Access",
    "drive_by_compromise": "Initial Access",
    "external_service_exploit": "Initial Access",
    # Execution (2.1b)
    "cmd_script_execution": "Execution",
    "wmi_execution": "Execution",
    "at_job": "Execution",
    "service_execution": "Execution",
    "msbuild_execution": "Execution",
    "python_execution": "Execution",
    # Persistence (2.1c)
    "startup_folder": "Persistence",
    "service_image_path_persistence": "Persistence",
    "appinit_dlls": "Persistence",
    "accessibility_feature": "Persistence",
    "ifeo_debugger": "Persistence",
    "netsh_helper": "Persistence",
    "logon_script": "Persistence",
    # Privilege escalation (2.1d)
    "uac_bypass": "Privilege Escalation",
    "se_debug_privilege": "Privilege Escalation",
    "named_pipe_impersonation": "Privilege Escalation",
    "unquoted_service_path": "Privilege Escalation",
    "always_install_elevated": "Privilege Escalation",
    # Defense evasion (2.1e)
    "disable_defender": "Defense Evasion",
    "disable_firewall": "Defense Evasion",
    "disable_audit": "Defense Evasion",
    "hidden_file_attribute": "Defense Evasion",
    "disable_system_restore": "Defense Evasion",
    # Credential access (2.1f)
    "lsass_dump": "Credential Access",
    "ntds_dump": "Credential Access",
    "password_store_theft": "Credential Access",
    "keylogging": "Credential Access",
    "network_sniffing": "Credential Access",
    "cached_credentials": "Credential Access",
    # Discovery (2.1g)
    "account_discovery": "Discovery",
    "share_discovery": "Discovery",
    "system_info_discovery": "Discovery",
    "domain_discovery": "Discovery",
    "security_software_discovery": "Discovery",
    "filesystem_discovery": "Discovery",
    # Lateral movement (2.1h)
    "smb_admin_share": "Lateral Movement",
    "rdp_lateral": "Lateral Movement",
    "winrm_lateral": "Lateral Movement",
    "ssh_lateral": "Lateral Movement",
    # Collection (2.1i)
    "clipboard_capture": "Collection",
    "screen_capture": "Collection",
    "archive_collection": "Collection",
    "local_data_collection": "Collection",
    # C2 / exfiltration (2.1j)
    "proxy_tool": "Exfiltration / C2",
    "unusual_port": "Exfiltration / C2",
    "encrypted_channel": "Exfiltration / C2",
    "exfil_alternative_protocol": "Exfiltration / C2",
    "exfil_web_service": "Exfiltration / C2",
}

#: Stag(es) whose presence makes the chain a *completed* campaign even when
#: only two families fired (exfiltration / lateral movement / C2).
TERMINAL_STAGES = {"Exfiltration / C2", "Lateral Movement"}

CORRELATION_THRESHOLD = 2  # distinct rule families -> correlated alert
MAX_STAGE_GAP_MINUTES = 60  # chain gap beyond which the chain is "slow burn"


class KillChainCorrelationRule(BaseRule):
    rule_id = "kill_chain_correlation"
    name = "Multi-Stage Attack Chain Detected"
    description = (
        "Multiple independent detection signals fired for the same user or "
        "source within the window, indicating a multi-stage attack campaign "
        "rather than isolated incidents."
    )
    severity = "critical"
    confidence = 0.85
    mitre_id = "T1071"
    recommendation = (
        "Treat this as a coordinated incident. Correlate the evidence events, "
        "assume deeper compromise, isolate affected hosts and rotate all "
        "affected credentials."
    )

    def __init__(
        self,
        session,
        threshold: int = CORRELATION_THRESHOLD,
        window_minutes: int = 60,
        max_stage_gap_minutes: int = MAX_STAGE_GAP_MINUTES,
    ):
        super().__init__(session)
        self.threshold = threshold
        self.window_minutes = window_minutes
        self.max_stage_gap_minutes = max_stage_gap_minutes

    def evaluate(self, window_minutes: int) -> list[DetectionResult]:
        since = datetime.now(timezone.utc) - timedelta(minutes=self.window_minutes or window_minutes)
        findings: list[DetectionResult] = []

        alerts = self.session.scalars(
            select(Alert).where(
                Alert.created_at >= since,
                Alert.status == "open",
                *self._org_conds(Alert),
            )
        ).all()

        by_group: dict[str, dict[str, datetime]] = {}
        for alert in alerts:
            key = self._group_key(alert)
            if key is None:
                continue
            stage = KILL_CHAIN_STAGES.get(alert.rule, "Other")
            first_seen = by_group.setdefault(key, {}).get(stage)
            created = alert.created_at
            if first_seen is None or (created is not None and created < first_seen):
                by_group[key][stage] = created

        for key, stages in by_group.items():
            if len(stages) < self.threshold:
                continue
            sequence, span_min, max_gap_min, ordered_ratio = self._timeline(stages)
            has_terminal = bool({s for s in stages} & TERMINAL_STAGES)
            ordered = True if ordered_ratio == 1.0 and len(sequence) > 1 else False
            slow = span_min > self.max_stage_gap_minutes
            evidence = (
                f"{len(stages)} independent detections correlated for '{key}' "
                f"({', '.join(sequence)}); "
                f"chain span {span_min:.1f} min, max inter-stage gap {max_gap_min:.1f} min"
            )
            if ordered:
                evidence += "; stages follow the canonical kill-chain order"
            elif len(sequence) > 1:
                evidence += f"; ordering deviates from the canonical sequence ({ordered_ratio:.0%} of adjacent pairs advance)"
            if slow:
                evidence += "; slow-burn chain (span exceeds stage-gap budget)"
            if has_terminal:
                evidence += "; includes a terminal stage (exfiltration/lateral movement)"
            confidence = min(0.98, 0.6 + len(stages) * 0.08 + (0.05 if ordered else 0.0))
            if slow and len(stages) <= self.threshold:
                confidence = max(0.5, confidence - 0.1)
            findings.append(
                self._result(
                    evidence=evidence,
                    event_ids=[],
                    severity="critical" if (has_terminal or len(stages) >= 3) else "high",
                    confidence=confidence,
                )
            )
        return findings

    @staticmethod
    def _timeline(stages: dict[str, datetime]) -> tuple[list[str], float, float, float]:
        """(ordered stage names, total span in minutes, max inter-stage gap,
        fraction of adjacent pairs advancing in canonical order).

        Only stages carrying a timestamp contribute to the timing analysis;
        stages without timestamps are appended at the end of the sequence.
        """
        order_index = {name: i for i, name in enumerate(KILL_CHAIN_STAGES.values())}
        timed = [(ts, name) for name, ts in stages.items() if ts is not None]
        timed.sort(key=lambda pair: pair[0])
        sequence = [name for _, name in sorted(timed, key=lambda pair: pair[0])]
        untimed = [name for name in stages if name not in sequence]
        sequence.extend(untimed)

        if len(timed) < 2:
            return sequence, 0.0, 0.0, 1.0 if len(sequence) <= 1 else 0.0

        first = timed[0][0]
        last = timed[-1][0]
        span_min = (last - first).total_seconds() / 60.0
        max_gap = 0.0
        for (t1, _), (t2, _) in zip(timed, timed[1:]):
            max_gap = max(max_gap, (t2 - t1).total_seconds() / 60.0)

        ordered_steps = 0
        # "Discovery" is phase-agnostic (recon legitimately precedes or sits
        # inside a campaign), so it is excluded from the strict ordering
        # pairwise check while still being reported in the timeline.
        strict = [s for s in sequence if s != "Discovery"]
        index_seq = [order_index.get(s, 9999) for s in strict]
        for a, b in zip(index_seq, index_seq[1:]):
            if b > a:
                ordered_steps += 1
        ratio = ordered_steps / max(len(index_seq) - 1, 1)
        return sequence, float(span_min), float(max_gap), float(ratio)

    @staticmethod
    def _group_key(alert: Alert) -> str | None:
        import re

        m = re.search(r"account '([^']+)'", alert.evidence)
        if m:
            return f"user:{m.group(1)}"
        m = re.search(r"from (\d{1,3}(?:\.\d{1,3}){3})", alert.evidence)
        if m:
            return f"ip:{m.group(1)}"
        return None
