"""Rule - Multi-Stage Kill-Chain Correlation.

Correlates otherwise-independent detections into a multi-stage incident.
If several rule families fired for the same user or host within the
window, a higher-severity correlated alert is raised (e.g. brute-force ->
persistence -> lateral movement).

Pure-live: operates on real alerts generated by the live pipeline.
"""
from __future__ import annotations

from datetime import datetime, timedelta, timezone

from sqlalchemy import select

from backend.database.models import Alert
from backend.detection.rules.base import BaseRule, DetectionResult

# Stages ordered by typical kill-chain progression.
KILL_CHAIN_STAGES = {
    "email_phishing": "Initial Access",
    "malware_file": "Initial Access / Tool Transfer",
    "brute_force": "Credential Access",
    "suspicious_powershell": "Execution",
    "privilege_escalation": "Privilege Escalation",
    "persistence": "Persistence",
    "data_staging": "Collection",
    "dns_http_exfil": "Exfiltration / C2",
    "lateral_movement": "Lateral Movement",
    "network_recon": "Discovery",
    "usb_device": "Lateral Movement",
}

CORRELATION_THRESHOLD = 2  # distinct rule families -> correlated alert


class KillChainCorrelationRule(BaseRule):
    rule_id = "kill_chain_correlation"
    name = "Multi-Stage Attack Chain Detected"
    description = (
        "Multiple independent detection signals fired for the same user or "
        "source within the window, indicating a multi-stage attack campaign "
        "rather than isolated incidents."
    )
    severity = "critical"
    confidence = 0.85
    mitre_id = "T1071"
    recommendation = (
        "Treat this as a coordinated incident. Correlate the evidence events, "
        "assume deeper compromise, isolate affected hosts and rotate all "
        "affected credentials."
    )

    def __init__(self, session, threshold: int = CORRELATION_THRESHOLD, window_minutes: int = 60):
        super().__init__(session)
        self.threshold = threshold
        self.window_minutes = window_minutes

    def evaluate(self, window_minutes: int) -> list[DetectionResult]:
        since = datetime.now(timezone.utc) - timedelta(minutes=self.window_minutes or window_minutes)
        findings: list[DetectionResult] = []

        alerts = self.session.scalars(
            select(Alert).where(Alert.created_at >= since, Alert.status == "open")
        ).all()

        by_user: dict[str, dict[str, str]] = {}
        for alert in alerts:
            key = self._group_key(alert)
            if key is None:
                continue
            stage = KILL_CHAIN_STAGES.get(alert.rule, "Other")
            by_user.setdefault(key, {})[stage] = alert.name

        for key, stages in by_user.items():
            if len(stages) < self.threshold:
                continue
            ordered = [s for s in KILL_CHAIN_STAGES.values() if s in stages]
            evidence = (
                f"{len(stages)} independent detections correlated for '{key}' "
                f"({', '.join(ordered)}): {', '.join(sorted(stages.values()))} "
                f"within {self.window_minutes} minutes - multi-stage kill chain."
            )
            findings.append(
                self._result(
                    evidence=evidence,
                    event_ids=[],
                    severity="critical",
                    confidence=min(0.98, 0.7 + len(stages) * 0.08),
                )
            )
        return findings

    @staticmethod
    def _group_key(alert: Alert) -> str | None:
        import re

        m = re.search(r"account '([^']+)'", alert.evidence)
        if m:
            return f"user:{m.group(1)}"
        m = re.search(r"from (\d{1,3}(?:\.\d{1,3}){3})", alert.evidence)
        if m:
            return f"ip:{m.group(1)}"
        return None
