"""Phase 7 incident configuration (spec 7.1, 7.9, 7.21, 7.35, 7.49)."""
from __future__ import annotations

INCIDENT_MODEL_VERSION: str = "1.0.0"
INCIDENT_ENGINE_VERSION: str = "1.0.0"

INCIDENT_ELIGIBILITY_ENABLED: bool = True
INCIDENT_FINGERPRINT_HASH_ALGO: str = "sha256"

INCIDENT_SLA_MINUTES: dict[str, int] = {
    "P1": 15,
    "P2": 30,
    "P3": 120,
    "P4": 480,
}

INCIDENT_CONFIDENCE_BASE: float = 0.40
INCIDENT_CONFIDENCE_CORRELATION: float = 0.20
INCIDENT_CONFIDENCE_MULTI_ENTITY: float = 0.10
INCIDENT_CONFIDENCE_REPEATED: float = 0.08
INCIDENT_CONFIDENCE_STRONG_EVIDENCE: float = 0.22
INCIDENT_MAX_CONFIDENCE: float = 1.0
INCIDENT_MIN_CONFIDENCE: float = 0.0

INCIDENT_SUPPRESSION_MAX_DAYS: int = 90
INCIDENT_SUPPRESSION_DEFAULT_EXPIRES_DAYS: int = 30

INCIDENT_MAX_TITLE_LENGTH: int = 200
INCIDENT_MAX_DESCRIPTION_LENGTH: int = 4000
INCIDENT_MAX_NOTE_LENGTH: int = 4000
INCIDENT_MAX_FEEDBACK_REASON_LENGTH: int = 1000

INCIDENT_DEFAULT_PRIORITY: str = "P3"
INCIDENT_DEFAULT_SEVERITY: str = "medium"


def get_sla_minutes(priority: str) -> int:
    return INCIDENT_SLA_MINUTES.get(priority.upper(), 480)
